README.md
Fixed the word mututally to mutually at the beginning of the README
=> Fixed a Typo in the README

CONTRIBUTING.md, README.md, package.json
- heroku build/deploy support added.
=> Heroku test

README.md
Fixed some other typos in the README
=> Fixed other typos in the README

client/src/components/LinkDisplay/index.js, client/src/pages/chatlink/index.js
Link generation ui using the copy to clipboard component
=> feat: link generation ui #2

README.md, backend/api/index.js
Added validateLink endpoint
closes #17
=> feat: check if channel is valid

client/public/index.html, client/src/Style.module.css, client/src/ThemeContext.js, client/src/components/Button/Style.module.css, client/src/components/Button/index.js, client/src/components/LinkDisplay/Style.module.css, client/src/components/LinkDisplay/index.js, client/src/components/Messaging/MessageList.js, client/src/components/Messaging/NewMessageForm.js, client/src/components/Messaging/UserStatusInfo.js, client/src/components/Messaging/styles/MessageList.module.css, client/src/components/Messaging/styles/NewMessageForm.module.css, client/src/components/Messaging/styles/UserStatusInfo.module.css, client/src/components/ThemeToggle/Style.module.css, client/src/components/ThemeToggle/index.js, client/src/index.js, client/src/pages/chatlink/Style.module.css, client/src/pages/chatlink/index.js, client/src/pages/messaging/Style.module.css, client/src/pages/messaging/index.js
Partial implementation of toggle, i.e, it is yet to be implemented on the messaging page. Awaiting reviews for coding practices and other stuff.
=> Dark Mode toggle #49

client/public/index.html, client/src/Style.module.css, client/src/ThemeContext.js, client/src/components/Button/Style.module.css, client/src/components/Button/index.js, client/src/components/LinkDisplay/Style.module.css, client/src/components/LinkDisplay/index.js, client/src/components/Messaging/MessageList.js, client/src/components/Messaging/NewMessageForm.js, client/src/components/Messaging/UserStatusInfo.js, client/src/components/Messaging/styles/MessageList.module.css, client/src/components/Messaging/styles/NewMessageForm.module.css, client/src/components/Messaging/styles/UserStatusInfo.module.css, client/src/components/ThemeToggle/Style.module.css, client/src/components/ThemeToggle/index.js, client/src/index.js, client/src/pages/chatlink/Style.module.css, client/src/pages/chatlink/index.js, client/src/pages/messaging/Style.module.css, client/src/pages/messaging/index.js
=> Dark Mode toggle #49 (#61)

backend/api/messaging/index.js, client/src/service/publicKey.js
=> refactor: change url structure for sharing and getting public key

backend/api/chatLink/index.js, backend/db/index.js
=> feat: added endpoint to patch chat-link as deleted

README.md, backend/api/chatLink/index.js, backend/api/messaging/index.js, client/src/service/getLink.js, client/src/service/sendMessage.js
=> fix: res api url structure

client/src/components/Messaging/Emoji/Style.module.css, client/src/components/Messaging/Emoji/index.js, client/src/components/Messaging/EmojiRow/Style.module.css, client/src/components/Messaging/EmojiRow/index.js, client/src/components/Messaging/NewMessageForm.js, client/src/components/Messaging/styles/NewMessageForm.module.css, client/src/utils/detectMobile.js
=> feat: emoji row

backend/socket.io/listeners.js
Resolves #113 by adding using async/await and try...catch
This is my first open source contribution so open to any feedback.
=> feat: Validate a channel before adding client to list

backend/socket.io/listeners.js, client/src/pages/messaging/index.js
=> feat: prevent more than 2 users

README.md, client/src/pages/chatlink/captcha.js, client/src/pages/chatlink/captcha.json, docker/Dockerfile, docker/README.md, package.json
1. Added `Dockerfile` in `docker/Dockerfile`. 
2. Added README describing the steps to build and run the docker image.
3. Added link in project's root `README.md` to Dockerfile's README.
4. Recaptcha client side key is provided as a json file in `client/src/pages/chatlink/captcha.json` ,  modified  `captcha.js` to read from the json config file instead of ENV.
5. Added `docker_start` to `scripts` in `package.json`, this will be used as the docker container entrypoint.
=> feat: Added Dockerfile

client/src/components/Messaging/ImagePicker/index.js
This solves the issue #125 where user can only select .jpeg/.png images.
=> feat:allow only images to be selected 

client/src/components/Messaging/styles/Message.module.css, client/src/components/Messaging/styles/ScrollWrapper.module.css
Issue #130 animate when new message appears
=> feat: new message animation issue #130

backend/api/messaging/index.js, client/src/components/Messaging/Message.js, client/src/components/Messaging/styles/Message.module.css, client/src/pages/messaging/index.js
For issue: Add timestamp to message #149
=> feat(timestamp): add message timestamp

backend/api/chatLink/index.js, backend/api/chatLink/utils/link.js, backend/api/chatLink/utils/pin.js
Added PIN generation function that generates 4 digits PIN based on UUID provided as per the algorithm mentioned in #150 .
Modified `CharLink.js` to return `pin` and `pinCreationTime` as per #152
=> feat:Added PIN generation

backend/api/chatLink/index.js
=> feat: pin api added

client/src/components/LinkDisplay/Style.module.css, client/src/components/LinkDisplay/index.js, client/src/components/PinDisplay/Style.module.css, client/src/pages/chatlink/index.js
Fix the issue #173 
Let me know if there's thing I need to change. It is my first time contributing, any critics is welcomed
=> fix: link/pin ui modification

backend/api/index.js
=> Updated the chat message

.env.sample, backend/api/messaging/index.js, backend/external/imagebb.js, backend/external/imgbb.js, backend/external/imgur.js, backend/external/uploadImage.js
I have made the following changes: 
> Integrated __*imgur*__ at backend/external/imagebb.js
>Inserted ```IMGUR_CLIENT_ID=''``` to .env.sample
Closes #117
=> added imgur

client/src/Style.module.css, client/src/components/Messaging/ImagePicker/Style.module.css
- Made some changes for mobile view.
- Some UI correction.
- Added backdrop blur for Image picker dialog box.
=> UI_cahnges

client/package-lock.json, client/package.json, client/src/components/Image/index.js, package-lock.json, package.json
Added zooming facility to the images
=> Added zooming facility to the images.

client/src/Style.module.css, client/src/components/Messaging/ImagePicker/Style.module.css, client/src/components/Messaging/RemoveButton/Style.module.css, client/src/components/Messaging/styles/NewMessageForm.module.css
- Message form corrections.
Issue : #186
=> Changes_to_Mobile_view

backend/db/index.js, client/src/pages/messaging/helpers/crypto.js, client/src/pages/messaging/helpers/index.js
immediately return this expression instead of assigning it to the temporary variable
=> fix: solving sonar javascript:S1488

.github/ISSUE_TEMPLATE/bug_report.md
Adding issue template for a bug report
=> docs: add bug report issue template

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, package-lock.json, package.json
Add to CONTRIBUTING link to env wiki to make it contributors easy to setup the development environment.
=> Add env wiki to CONTRIBUTING

.github/ISSUE_TEMPLATE/bug_report.md, package-lock.json, package.json
changing the node-fetch version to 2
fixes #210
=> Fix node fetch version

docker/Dockerfile, docker/README.md
[refactor: removed captcha](https://github.com/muke1908/chat-e2ee/pull/163/commits/777a5e5d0ab2563465fd38a0811a618155a3a289)
=> refactor: removed recaptcha in docker

.all-contributorsrc, client/src/Style.module.css, client/src/index.js, client/src/pages/chatlink/Style.module.css, client/src/pages/chatlink/index.js
Fixed issue #272 
Did some ui enhancements.
The background color is not covering the whole page. (Fixed)
=> ui-changes fixed-#272

.all-contributorsrc, client/src/Style.module.css, client/src/index.js, client/src/pages/chatlink/Style.module.css, client/src/pages/chatlink/index.js
Reverts muke1908/chat-e2ee#273
cc @Aditya-13
=> Revert "ui-changes fixed-#272"

client/public/index.html, client/src/Style.module.css
Remove font import from external source
=> Remove external font

backend/api/chatLink/utils/validateChannel.test.ts
Added a unit test for the channelValid function.
=> for Issue #268 - channelValid test

package-lock.json, service/package-lock.json, service/src/makeRequest.ts, service/src/sdk.ts
Added two new functions (setConfig, and configContext) in sdk.ts and exported them. Imported configContext in makeRequest.ts and used it in makeRequest function with BASE_URI to allow users to set a base url.
=> Kaleb Armbrust Issue #288 - Allow to set server endpoint

client/src/ThemeContext.js, client/src/components/ThemeToggle/index.js, client/src/pages/messaging/helpers/crypto.js, client/src/pages/messaging/helpers/index.js, client/src/pages/messaging/index.js, client/src/utils/storage.js
This PR is aimed to resolve #114. The patch is ready and haven't test it yet. I was sick and couldn't touch my computer easily during the last 3 days. Alhamdullilah I'm okay. I would like to point out that the patch is over-simplified to require a full on test. But that's not up to me.
I have provided very simple functionlities to the storage utility for in case the conversation goes beyond 5MB of size to be mitigation solutions later.
I would like to point out an important note that the messages are stored **without** encryption. This is mostly due to the storage limitations of the **Session Storage** [see here](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria).
Sorry for being late. Testing was very buggy to deal with for me to finish it …
=> Store messages in session storage

README.md
I have corrected the links for developer section.
This is my first open source contribution :)
=> feat: correction for developer section link in readme file

client/package-lock.json, client/src/pages/chatlink/index.tsx, package-lock.json, service/package-lock.json
=> fix : loading text added to Create Link Button

.gitignore, client/src/components/Messaging/NewMessageForm.tsx, package-lock.json
On client the form submission of the message was handled incorrectly. I fixed that issue.
=> fix: on message send preventDefault error

service/src/public/types.ts, service/src/sdk.ts
added param in setchannel and stored in ChatE2EE class
=> added param in setchannel and stored in ChatE2EE class

client/package-lock.json, client/package.json, client/src/components/LinkDisplay/Style.module.css, client/src/components/LinkDisplay/index.tsx
Implemented functionality to generate QR codes for chat links in the LinkDisplay component. Users can now easily access and share QR codes for their chat sessions.
=> feat: Add QR code generation for chat link

client/package-lock.json, client/package.json, client/src/components/LinkDisplay/Style.module.css, client/src/components/LinkDisplay/index.tsx
Reverts muke1908/chat-e2ee#338
=> Revert "feat: Add QR code generation for chat link"

client/src/components/Messaging/ScrollWrapper.tsx, client/src/components/Messaging/styles/ScrollWrapper.module.css
=> fix new messages auto scroll issue

README.md
Found some errors in grammar / spelling when reading over the project description. Fixed them here.
=> Improved documentation for clarity

client/package.json, client/src/components/LinkDisplay/index.tsx
=> perf: enhance QR code clarity using QRCodeSVG
